In [ ]:
pip install numpy


In [4]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
random = np.random.rand(3,3)
print(random)

[[0.77325378 0.83012803 0.09637882]
 [0.83929706 0.81325401 0.45100551]
 [0.46037628 0.713282   0.66128823]]


In [ ]:
evenArray = np.arange(10,50,2)
print(evenArray)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
identityMatrix = np.identity(5);
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
reshapeArray = np.arange(20)
reshapeArray.reshape((5,4))
print(reshapeArray)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
test = np.array(())
np.transpose(reshapeArray,test)

TypeError: ignored

In [ ]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

In [ ]:
matrix1 = np.array(((12,24,2),(45,5,2)))
print(matrix1)
matrix2 = np.array(((4,5,6),(2,5,8)))
print(matrix2)
print(np.add(matrix1,matrix2))

[[12 24  2]
 [45  5  2]]
[[4 5 6]
 [2 5 8]]
[[16 29  8]
 [47 10 10]]


In [ ]:
np.max(matrix1)

45

IndexError: ignored

In [7]:
test = np.array(([1, 2,5], [3, 4,7], [5, 6,9]))
test[:, 1]

array([2, 4, 6])

In [10]:
np.diag(test)

array([1, 4, 9])

In [13]:
rand_vals = np.random.randint(1, 101, size=5)
rand_vals

array([58, 42, 34, 75, 10])

In [14]:
np.random.randint(1, 101, size=(5,5))

array([[33,  9, 65, 61, 69],
       [19,  9, 63, 93,  2],
       [83, 75, 31, 92, 69],
       [44, 55, 34, 26, 62],
       [34, 25, 60, 20, 12]])

In [18]:
np.random.shuffle(rand_vals)
rand_vals

array([75, 58, 10, 34, 42])

In [19]:
np.random.poisson(lam=1.0, size=10)

array([2, 0, 1, 0, 2, 2, 1, 0, 1, 2])

In [20]:
 np.random.uniform(low=0.5, high=13.3, size=(5,3))

array([[ 5.81835636, 10.80104699,  9.42778987],
       [ 1.25441486, 10.0515808 ,  6.70024932],
       [ 8.27839708,  3.44045983,  0.67820601],
       [ 6.92312479,  5.1954956 , 10.77326291],
       [11.70115248, 11.5963143 ,  9.71405683]])

In [27]:
a = np.arange(-10,15)
a[a > 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a[a % 3 == 0]

array([-9, -6, -3,  0,  3,  6,  9])

In [24]:
mask = [0,1,0,0,0,1,0]
np.ma.masked_array(a[a % 3 == 0],mask)

masked_array(data=[-9, --, -3, 0, 3, --, 9],
             mask=[False,  True, False, False, False,  True, False],
       fill_value=999999)

In [28]:
a[a > 10]

array([11, 12, 13, 14])

In [30]:
m = np.random.uniform(low=0.5, high=13.3, size=(5,3))
m[m > 5]

array([ 9.12549043,  5.54786121,  6.04913174,  7.70940029,  9.29170531,
       11.43337452, 10.44973284,  9.39570789,  7.77282772, 12.36952142])

In [36]:
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))
xarr
R1 = np.corrcoef(xarr)
R1
yarr = rng.random((3, 3))
yarr
R2 = np.corrcoef(xarr, yarr)
R2


array([[ 1.        ,  0.99256089, -0.68080986,  0.75008178, -0.934284  ,
        -0.99004057],
       [ 0.99256089,  1.        , -0.76492172,  0.82502011, -0.97074098,
        -0.99981569],
       [-0.68080986, -0.76492172,  1.        , -0.99507202,  0.89721355,
         0.77714685],
       [ 0.75008178,  0.82502011, -0.99507202,  1.        , -0.93657855,
        -0.83571711],
       [-0.934284  , -0.97074098,  0.89721355, -0.93657855,  1.        ,
         0.97517215],
       [-0.99004057, -0.99981569,  0.77714685, -0.83571711,  0.97517215,
         1.        ]])

In [38]:
np.percentile(a, 75, axis=0)

8.0

In [43]:
x = y = z = np.arange(0.0,5.0,1.0)
np.savetxt('C:\\Users\\A_\\Desktop\\test.txt', x, delimiter=',')



---



---

