In [11]:
#Multiply each element in an array by a scalar:
import numpy as np

array = np.array([1, 2, 3, 4])
scalar = 2
result = array * scalar
print(result)

[2 4 6 8]


In [12]:
#Add a 1D array to each row of a 2D array using broadcasting:

array_2d = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array_1d = np.array([1, 2, 3])
result = array_2d + array_1d[:, np.newaxis]
print(result)

[[2 2 2]
 [4 4 4]
 [6 6 6]]


In [3]:
#Multiply corresponding elements of two arrays with different shapes using broadcasting:

array_1 = np.array([1, 2, 3])
array_2 = np.array([[4, 5, 6], [7, 8, 9]])
result = array_1[:, np.newaxis] * array_2

ValueError: ignored

In [13]:
#Calculate the outer product of two arrays:

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
result = np.outer(array_1, array_2)
print(result)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [14]:
#Apply a custom function element-wise to an array:

array = np.array([1, 2, 3, 4])
result = np.sqrt(array)
print(result)

[1.         1.41421356 1.73205081 2.        ]


In [7]:
#File I/O:

#Save a NumPy array to a text file:

array = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('array.txt', array)

In [8]:
#Load a NumPy array from a text file:

loaded_array = np.loadtxt('array.txt')


In [9]:
#Save a NumPy array to a binary file:

np.save('array.npy', array)

#Load a NumPy array from a binary file:

loaded_array = np.load('array.npy')

#Save multiple arrays to a single compressed NPZ file:

np.savez('array.npz', array1=array_1, array2=array_2)
loaded_data = np.load('array.npz')
loaded_array1 = loaded_data['array1']
loaded_array2 = loaded_data['array2']


In [17]:
#exercice 03:

import numpy as np

# Create the vector V
V = np.array([0.5, 0.8, 0.9])

# Create the matrix M, M transpose, Matrix G = M * M transpose
M = np.array([[1.0, 0.3, 0.65], [0.5, 0.8, 0.9], [1.0, 0.3, 0.65]])
M_transpose = np.transpose(M)
G = np.dot(M, M_transpose)
print("1")
print(G)

# Extract vector 1, row 1, sub matrix (0-2,0-2)
vector1 = M[0]
row1 = M[0, :]
sub_matrix = M[0:3, 0:3]
print("2")
print(sub_matrix)

# Find max, min, sum, and average of each
max_sub_matrix = np.max(sub_matrix)
min_sub_matrix = np.min(sub_matrix)
sum_sub_matrix = np.sum(sub_matrix)
average_sub_matrix = np.mean(sub_matrix)
print("3")
print(average_sub_matrix)
# Extract from M: (a) diagonal matrix, (b) identity matrix, (c) values bigger than 0.5
diagonal_matrix = np.diag(M)
identity_matrix = np.identity(3)
values_bigger_than_05 = M[M > 0.5]
print("4")
print(values_bigger_than_05)

# Insert a new row and a new column to M using random values
new_row = np.random.rand(1, 3)
M = np.vstack([M, new_row])
new_column = np.random.rand(4, 1)
M = np.hstack([M, new_column])
print("5")
print(M)

# Calculate Euclidean distance of each two vectors of M using G
euclidean_distances = np.sqrt(np.sum(np.square(G), axis=1))
print("6")
print(euclidean_distances)

# Verify if V is in M
is_V_in_M = np.all(np.isin(V, M))
print("7")
print(is_V_in_M)

# Create a random sample of data (X values, and Y values)
X = np.linspace(0, 11, 10)
a = np.random.uniform(1.5, 1.8)
b = np.random.uniform(4, 4.5)
Y = a * X + b
print("8")
print(Y)

# Check if matrix N is a sub matrix of M
N = np.random.rand(2, 2)
is_N_submatrix_of_M = np.all(np.isin(N, M))
print("10")
print(is_N_submatrix_of_M)

# Create matrices of size (5, 5) containing (a) ones, (b) zeros, and (c) random values
print("11")
matrix_ones = np.ones((5, 5))
print("12")
matrix_zeros = np.zeros((5, 5))
print("13")
matrix_random = np.random.rand(5, 5)


1
[[1.5125 1.325  1.5125]
 [1.325  1.7    1.325 ]
 [1.5125 1.325  1.5125]]
2
[[1.   0.3  0.65]
 [0.5  0.8  0.9 ]
 [1.   0.3  0.65]]
3
0.6777777777777778
4
[1.   0.65 0.8  0.9  1.   0.65]
5
[[1.         0.3        0.65       0.2375432 ]
 [0.5        0.8        0.9        0.52568371]
 [1.         0.3        0.65       0.88706414]
 [0.10346789 0.34103403 0.44737312 0.84575711]]
6
[2.51613543 2.53006917 2.51613543]
7
True
8
[ 4.21141545  6.11964303  8.02787062  9.9360982  11.84432578 13.75255336
 15.66078095 17.56900853 19.47723611 21.38546369]
10
False
11
12
13
